### ISSUE TITLE
Backtick Code Block style doesn't work

### ISSUE THREAD

**Issue by hoschi** [Jamling/hexo-filter-highlight#1]
I try to get this working, but only codeblock style works for me.

This works:
{% codeblock lang:objc %}
[rectangle setX: 10 y: 10 width: 20 height: 20];
{% endcodeblock %}

This doesn't :
``` objc
[rectangle setX: 10 y: 10 width: 20 height: 20];
```

Have you an idea what is causing this?

**Comment by hoschi** [comment]
I see another problem: titles are not rendered when using codeblock
{% codeblock myTitle lang:objc %}
[rectangle setX: 10 y: 10 width: 20 height: 20];
{% endcodeblock %}

**Comment by Jamling** [comment]
@hoschi 
{% codeblock lang:objc %} is the highlight of hexo.
the hexo-filter-highlight works for hexo which closed the default highlight.

**Comment by Jamling** [comment]
my test:

### codeblock

{% codeblock lang:objc %}
[rectangle setX: 10 y: 10 width: 20 height: 20];
{% endcodeblock %}

### backtick

``` objc
[rectangle setX: 10 y: 10 width: 20 height: 20];
```

And the output is: 
![compare](https://cloud.githubusercontent.com/assets/5350591/18784147/d54d92aa-81c2-11e6-841d-aba4afda4651.png)

So:
- codeblock is rendered by hexo self, it detected the language is `ini`
- blacktick is rendered by hexo-filter-highlight, it detected the language is `objectivec`

**Comment by hoschi** [comment]
Strange, than someting doesn't work right.

This is my test blog post (escaped backticks so Github doesn't parse them):

```
title: "test"
date: 2016-09-23 08:33:01
---

Codeblock:
{% codeblock myTitle lang:objc %}
[rectangle setX: 10 y: 10 width: 20 height: 20];
{% endcodeblock %}

Single Backtick:
`
[rectangle setX: 10 y: 10 width: 20 height: 20];
`

Three Backticks:
\`\`\`
[rectangle setX: 10 y: 10 width: 20 height: 20];
\`\`\`

```

Which renders:
![2016-09-23-155620_1199x369_scrot](https://cloud.githubusercontent.com/assets/163128/18788203/46e922ca-81a6-11e6-83fa-4daae44f78a8.png)

_config.yml:

```
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Stefan Gojan
subtitle:
description:
author: Stefan Gojan
language: de
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://foo-bar.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: mine

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    # fix toc comments
    html: true

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

# hexo-filter-plugin (https://github.com/Jamling/hexo-filter-highlight) config
## highlight in frontend, the plugin (backend) just do some prepare work.
## you need to read the docs on https://github.com/Jamling/hexo-filter-highlight to getting start
hljs:
  enable: true #true to enable the plugin
  line_number: frontend # add line_number in frontend or backend
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
```

Script tags copied from readme to fetch highlight.js. JS code for formatting in browser:

```
$(document).ready(function() {
    // highlight code
    hljs.initHighlightingOnLoad();

});
```

**Comment by Jamling** [comment]
As your description, the hexo-filter-highlight works wrong, please tell me it's version, it may caused by the markdown config. Try to change to :

``` yaml
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
```

and try again
